apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://87.248.154.24/root/blog-platform.git'
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: blog-ops
  syncPolicy:
    automated:
      prune: true      
      selfHeal: true   
    syncOptions:
      - CreateNamespace=true
