apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
type: Opaque
stringData:
  # Database
  POSTGRES_USER: "blog_user"
  POSTGRES_PASSWORD: "blog_pass"
  POSTGRES_DB: "blog_db"
  DATABASE_URL: "postgresql://blog_user:blog_pass@postgres-service:5432/blog_db"
  
  # Flask
  SECRET_KEY: "production-super-secret-key"
  
  # MinIO
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
