apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-secrets.yaml
  - 02-configmap.yaml
  - 03-postgres.yaml
  - 04-minio.yaml
  - 05-redis.yaml
  - 06-backend.yaml
  - 07-frontend.yaml
  - 08-ingress.yaml
