apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: blog-ops
data:
  FLASK_CONFIG: "production"
  FLASK_APP: "run.py"
  S3_BUCKET: "blog-images"
  S3_REGION: "us-east-1"
  # Internal URL for Backend -> MinIO communication
  S3_ENDPOINT: "http://minio-service:9000"
